# Generated by Django 4.1.4 on 2022-12-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_id",
                    models.CharField(max_length=16, unique=True, verbose_name="班号"),
                ),
                (
                    "class_semester",
                    models.SmallIntegerField(
                        choices=[
                            (1, "大一上"),
                            (2, "大一下"),
                            (3, "大二上"),
                            (4, "大二下"),
                            (5, "大三上"),
                            (6, "大三下"),
                            (7, "大四上"),
                            (8, "大四下"),
                        ],
                        default=1,
                        verbose_name="学期",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(max_length=16, unique=True, verbose_name="课程号"),
                ),
                ("course_name", models.CharField(max_length=32, verbose_name="课程名")),
                (
                    "course_credit",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=2, verbose_name="学分"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Majors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major_id",
                    models.CharField(max_length=16, unique=True, verbose_name="专业号"),
                ),
                (
                    "major_name",
                    models.CharField(max_length=32, unique=True, verbose_name="专业名"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_id",
                    models.CharField(max_length=16, unique=True, verbose_name="工号"),
                ),
                ("teacher_name", models.CharField(max_length=16, verbose_name="姓名")),
                ("teacher_age", models.IntegerField(verbose_name="年龄")),
                (
                    "teacher_gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=16, unique=True, verbose_name="学号"),
                ),
                ("student_name", models.CharField(max_length=16, verbose_name="姓名")),
                (
                    "student_gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                ("student_age", models.IntegerField(verbose_name="年龄")),
                ("student_birthday", models.DateField(verbose_name="出生年月")),
                (
                    "classes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SMS_MYSQL.classes",
                        to_field="class_id",
                        verbose_name="班级",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classes",
            name="majors",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="SMS_MYSQL.majors",
                to_field="major_id",
                verbose_name="专业",
            ),
        ),
        migrations.CreateModel(
            name="TeachingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tp_type",
                    models.SmallIntegerField(
                        choices=[(1, "必修"), (2, "选修")], verbose_name="课程性质"
                    ),
                ),
                (
                    "tp_semester",
                    models.SmallIntegerField(
                        choices=[
                            (1, "大一上"),
                            (2, "大一下"),
                            (3, "大二上"),
                            (4, "大二下"),
                            (5, "大三上"),
                            (6, "大三下"),
                            (7, "大四上"),
                            (8, "大四下"),
                        ],
                        verbose_name="学期",
                    ),
                ),
                (
                    "courses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SMS_MYSQL.courses",
                        to_field="course_id",
                        verbose_name="课程",
                    ),
                ),
                (
                    "majors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SMS_MYSQL.majors",
                        to_field="major_id",
                        verbose_name="专业",
                    ),
                ),
            ],
            options={
                "unique_together": {("majors", "courses")},
            },
        ),
        migrations.CreateModel(
            name="TeacherSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SMS_MYSQL.classes",
                        to_field="class_id",
                        verbose_name="班级",
                    ),
                ),
                (
                    "courses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SMS_MYSQL.courses",
                        to_field="course_id",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teachers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SMS_MYSQL.teachers",
                        to_field="teacher_id",
                        verbose_name="老师",
                    ),
                ),
            ],
            options={
                "unique_together": {("teachers", "classes")},
            },
        ),
        migrations.CreateModel(
            name="StudentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resit",
                    models.SmallIntegerField(
                        choices=[(1, "是"), (0, "否")], verbose_name="是否补考"
                    ),
                ),
                (
                    "courses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SMS_MYSQL.courses",
                        to_field="course_id",
                        verbose_name="课程",
                    ),
                ),
                (
                    "students",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SMS_MYSQL.students",
                        to_field="student_id",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "unique_together": {("students", "courses")},
            },
        ),
    ]
