# Generated by Django 4.1.4 on 2022-12-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SMS_MYSQL", "0002_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="teachers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="SMS_MYSQL.teachers",
                to_field="teacher_id",
                verbose_name="授课教师",
            ),
        ),
        migrations.DeleteModel(
            name="TeacherSchedule",
        ),
    ]
