# Generated by Django 4.1.4 on 2022-12-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SMS_MYSQL", "0004_remove_studentcourse_teachers_teacherschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachers",
            name="teacher_age",
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="resit",
            field=models.SmallIntegerField(
                choices=[(1, "否"), (2, "是")], default=1, verbose_name="是否补考"
            ),
        ),
    ]
