# Generated by Django 4.1.4 on 2022-12-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SMS_MYSQL", "0005_remove_teachers_teacher_age_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeacherSchedule",
            new_name="TeacherDuty",
        ),
    ]
