# Generated by Django 4.1.4 on 2022-12-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SMS_MYSQL", "0006_rename_teacherschedule_teacherduty"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeacherDuty",
            new_name="TeachingDuty",
        ),
    ]
