# Generated by Django 4.1.4 on 2022-12-16 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SMS_MYSQL", "0007_rename_teacherduty_teachingduty"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="grade",
            field=models.SmallIntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="成绩",
            ),
        ),
    ]
