# Generated by Django 4.1.4 on 2022-12-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SMS_MYSQL", "0010_alter_studentcourse_resit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="student_age",
        ),
        migrations.AlterField(
            model_name="classes",
            name="class_semester",
            field=models.SmallIntegerField(
                choices=[
                    (0, "大一上"),
                    (1, "大一下"),
                    (2, "大二上"),
                    (3, "大二下"),
                    (4, "大三上"),
                    (5, "大三下"),
                    (6, "大四上"),
                    (7, "大四下"),
                ],
                default=0,
                verbose_name="学期",
            ),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="resit",
            field=models.SmallIntegerField(
                choices=[(0, "否"), (1, "是")], default=0, verbose_name="是否补考"
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="student_birthday",
            field=models.DateField(blank=True, null=True, verbose_name="出生年月"),
        ),
        migrations.AlterField(
            model_name="students",
            name="student_gender",
            field=models.SmallIntegerField(
                choices=[(0, "男"), (1, "女")], default=0, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="teacher_gender",
            field=models.SmallIntegerField(
                choices=[(0, "男"), (1, "女")], default=0, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="teachingplan",
            name="tp_semester",
            field=models.SmallIntegerField(
                choices=[
                    (0, "大一上"),
                    (1, "大一下"),
                    (2, "大二上"),
                    (3, "大二下"),
                    (4, "大三上"),
                    (5, "大三下"),
                    (6, "大四上"),
                    (7, "大四下"),
                ],
                default=0,
                verbose_name="学期",
            ),
        ),
        migrations.AlterField(
            model_name="teachingplan",
            name="tp_type",
            field=models.SmallIntegerField(
                choices=[(0, "选修"), (1, "必修")], default=0, verbose_name="课程性质"
            ),
        ),
    ]
