# Generated by Django 4.1.4 on 2022-12-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SMS_MYSQL", "0011_remove_students_student_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_credit",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=3, verbose_name="学分"
            ),
        ),
    ]
